- name: installing supervisor into virtualenv
  pip:
    name=supervisor
    virtualenv={{ sv_virtualenv }}
    state=present

- name: ensuring required supervisor directories
  file: >
    path="{{ sv_virtualenv }}/etc/supervisor/conf.d"
    state=directory

- name: installing supervisor configuration
  template: >
    src=supervisord.conf.j2 
    dest="{{ sv_virtualenv }}/etc/supervisor/supervisord.conf"
  notify: reload supervisor

- name: installing supervisor http server
  when: sv_http
  template: >
    src=supervisor-http.ini.j2
    dest="{{ sv_virtualenv }}/etc/supervisor/conf.d/supervisor-http.ini"
    mode=754
  notify: reload supervisor

- name: Check if socket exists supervisor running
  stat: path="{{ sv_virtualenv }}/etc/supervisor/supervisord.sock"
  register: check_supervisor_running

- name: running supervisord
  shell: chdir={{ sv_virtualenv }}/etc/supervisor
    {{ sv_virtualenv }}/bin/supervisord -c {{ sv_virtualenv }}/etc/supervisor/supervisord.conf
  when: not check_supervisor_running.stat.exists
