language: python
python:
  - "2.7"

services:
  - docker


before_install:
- docker pull postgres

# command to install dependencies
install:
 - "pip install -r requirements.txt"
 - "pip install -r requirements_dev.txt"
 - "pip install -e ."
# command to run tests
script: py.test

after_success:
  - coveralls