- name: Check directories
  file: path={{ item }} state=directory
  with_items: 
    - "{{ sm_log_dir }}"

- name: create logfile
  file: path={{ sm_log_dir }}/supervisor_{{ sm_app_name }}.out.log state=touch

- name: Copy config file
  template: src={{ sm_app_ini_template }} dest={{ sm_supervisor_config_dir }}/{{ sm_app_name }}.ini
  notify: reload supervisor job

- name: Register Supervisor job
  supervisorctl: >
    state=present
    name={{ sm_app_name }}
    supervisorctl_path={{ sm_supervisorctl_path }}
    config={{ sm_supervisor_config }}
  notify: reload supervisor job
