---
- hosts: all
  sudo: yes
  tasks:
  - name: Install base packages
    apt: name={{ item }} update_cache=no force=no state=installed
    with_items:
    - build-essential
    - ntp
    - htop
    - git
    - python-dev
    - python-pip
    - python-pycurl
    - python-virtualenv
    - supervisor
    - curl

  - name: add backports repository
    apt_repository: repo='deb http://http.debian.net/debian wheezy-backports main' state=present

  - name: install new kernel from backports
    apt: name=linux-image-amd64 state=latest default_release=wheezy-backports update_cache=yes

  - name: install docker with evil internetscript
    shell: curl -sSL https://get.docker.com/ | sh